remove 2nd column

diff --git a/W0CHP-pistar b/W0CHP-pistar
--- a/W0CHP-pistar
+++ b/W0CHP-pistar
@@ -120,9 +120,18 @@ function InstallDashboard() {
             apt-get install -y php7.3-xml
 	else # damn - need to install an old version :-/
 	    curl $REQD_PACKS_REPO/php7.0-xml_7.0.33-0+deb9u3_armhf.deb -o /tmp/php7.0-xml_7.0.33-0+deb9u3_armhf.deb
-            dpkg -i /tmp/php7.0-xml_7.0.33-0+deb9u3_armhf.deb
-	    apt-get install -f
-	    rm /tmp/php7.0-xml_7.0.33-0+deb9u3_armhf.deb
+	    curl $REQD_PACKS_REPO/php7.0-xml_7.0.33-0+deb9u3_armhf.deb.md5sum -o /tmp/php7.0-xml_7.0.33-0+deb9u3_armhf.deb.md5sum
+            PACK_MD5=`cat /tmp/php7.0-xml_7.0.33-0+deb9u3_armhf.deb.md5sum | cut -d' ' -f1`
+            GET_DL_MD5=`md5sum /tmp/php7.0-xml_7.0.33-0+deb9u3_armhf.deb.md5sum | cut -d' ' -f1`
+            if  [ "${PACK_MD5}" == "${GET_DL_MD5}" ]; then
+                dpkg -i /tmp/php7.0-xml_7.0.33-0+deb9u3_armhf.deb
+	        apt-get install -f
+	        rm -rf /tmp/php7.0-xml_7.0.33-0+deb9u3_armhf*
+            else
+                echo -e "MD5 integrty check for php7.0-xml_7.0.33-0+deb9u3_armhf.deb failed!\n"
+                echo -e "You can try re-running this script to re-download the package.\n"
+                exit 1
+            fi
 	fi
     else
 	echo -e "\nThe required 'php-xml' package was already found! NOT intalling.\n"
