* Minor: Detect other 3rd party fork and bail if TRUE

diff --git a/WPSD-Installer b/WPSD-Installer
--- a/WPSD-Installer
+++ b/WPSD-Installer
@@ -89,6 +89,10 @@ RELEASE_FILE="/etc/pistar-release"
 if [ -f ${RELEASE_FILE} ]; then
     PISTAR_VERSION=$(grep 'Version' /etc/pistar-release | cut -f 2 -d '=' | tr -d ' ')
     PISTAR_VERSION_INFO=( ${PISTAR_VERSION//./ })
+    if [[ $(grep 'RMB' ${RELEASE_FILE}) ]] ; then
+        echo -e "\n${CROSS} ${COL_BRIGHT_RED}ERROR:${COL_NC} Detected F1RMB installation. Only pristine Pi-Star installations are supported.\n    You must uninstall F1RMB first."
+	exit 1
+    fi
     if [[ ${PISTAR_VERSION_INFO[0]} -ne ${SUPPORTED_MAJOR} ]] || [[ ${PISTAR_VERSION_INFO[2]} -lt ${SUPPORTED_MIN_MIN} ]]; then
         echo -e "\n${CROSS} ${COL_BRIGHT_RED}ERROR:${COL_NC} Only Pi-Star 4.1.6 or above is supported.\n"
         exit 1
